# @package _global_
defaults:
  - sam_hybrid_base@model
  - _self_
  - /training: sam_training

trainer:
  _target_: trainers.sam_trainer.SAMTrainer

model:
  name: E0_AL_DF
  adaptation_mode: encoder_frozen_alignment_decoder_ft
  alignment_num_blocks: 2
