# @package _global_
defaults:
  - sam_hybrid_base@model
  - _self_
  - /training: sam_training

trainer:
  _target_: trainers.sam_trainer.SAMTrainer

model:
  name: E0_DL
  adaptation_mode: encoder_frozen_decoder_lora
