# @package _global_
defaults:
  - sam_hybrid_base@model
  - _self_
  - /training: sam_training

trainer:
  _target_: trainers.sam_trainer.SAMTrainer

model:
  name: EL_DF
  adaptation_mode: encoder_conv_lora_decoder_ft
