# @package _global_
defaults:
  - _self_
  - /training: sam_training

trainer:
  _target_: trainers.sam_trainer.SAMTrainer

model:
  name: sam
  _target_: model.sam_hybrid_adapter.LoRA_Sam
  sam_type: vit_b
  img_size: ${data.img_size}
  num_classes: ${data.num_classes}
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  encoder_mode: "conv_lora"
  decoder_mode: "lora"
  use_alignment: false
  r_e: 4
  r_d: 4
  alignment_num_blocks: 4
  alignment_hidden_channels: 256
  conv_lora_expert_num: 4
  checkpoint: null
