# @package _global_

# Training settings
training:
  lr: 0.0001                      # Learning rate
  batch_size: 64
  num_epochs: 500
  warmup_epochs: 5
  train_head_only: true           # Train only decoder parts
  num_workers: 8
  save_interval: 20               # Save checkpoint every N epochs
  limit_train_batches: null       # For debugging purposes, limit number of batches per epoch
  dice_weight: 0.8                # Weight for Dice loss in combined loss
  early_stopping:
    enabled: true
    patience: 20
    min_delta: 1e-6

# Optimizer configuration
optimizer:
  _target_: torch.optim.AdamW
  lr: ${training.lr}
  weight_decay: 0.01
  betas: [0.9, 0.999]
  # Custom flags for TinyUSFMTrainer
  use_layer_decay: true
  num_layers: 12
  layer_decay: 0.8
  gradient_clip:
    max_norm: 1.0

# Scheduler settings
scheduler:
  _target_: utils.schedule.WarmupPolyLR
  warmup_epochs: ${training.warmup_epochs}
  max_epochs: ${training.num_epochs}
  base_lr: ${training.lr}
  end_lr: 1e-6
  power: 0.9

hardware:
  n_gpus: 1
  seed: 42
  deterministic: 1
  gpu_ids: [0]

# Output configuration
output:
  dir: logs
  is_pretrain: true               # Pretrained or scratch

# Task settings
task:
  type: organ                     # tumor or organ

# Visualization
visualization:
  num_samples: 10                 # Number of samples to visualize during test

# WandB configuration
wandb:
  project: medical_foundation_models
  entity: hheo
