# Student model configuration for distillation (SAM as student)
name: sam
_target_: model.sam_hybrid_adapter.LoRA_Sam
sam_type: vit_b
img_size: ${data.img_size}
num_classes: ${data.num_classes}
pixel_mean: [123.675, 116.28, 103.53]
pixel_std: [58.395, 57.12, 57.375]
encoder_mode: "ft"
decoder_mode: "ft"
use_alignment: false
r_e: 4
r_d: 4
alignment_num_blocks: 4
alignment_hidden_channels: 256
conv_lora_expert_num: 4
checkpoint: null
exp_id: null
