# Teacher model configuration for distillation (TinyUSFM as teacher)
name: TinyUSFM
_target_: model.tinyusfm_seg.SegmentationModel
num_classes: ${data.num_classes}
checkpoint: experiment_results/TinyUSFM_binary_ft/checkpoints/best_epoch_59_dice_0.8043.pth
use_alignment: false
img_size: ${data.img_size}
