# Teacher model configuration for distillation (TinyUSFM as teacher)
name: TinyUSFM
_target_: model.tinyusfm_seg.SegmentationModel
num_classes: ${data.num_classes}
checkpoint: "logs/train/TinyUSFM/20260326_170811_bs8_lr0.0001/checkpoints/best_epoch_59_dice_0.8019.pth"
use_alignment: false
img_size: ${data.img_size}
